# Imports

In [1]:
import os
import warnings
from rich import print

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import anndata as ad

import scanpy as sc

In [2]:
plt.rcParams['savefig.dpi'] = 300
%matplotlib inline

# Load Datasets

## Morarach E15.5

In [3]:
morarach_e15_ad = sc.read_h5ad('preprocessed_datasets/morarach_E15.h5ad')

In [4]:
morarach_e15_ad.X = morarach_e15_ad.layers['raw_counts']

In [5]:
morarach_e15_ad.obs['barcode'] = morarach_e15_ad.obs_names

In [6]:
morarach_e15_ad.obs['age'] = 'E15.5'
morarach_e15_ad.obs['dataset'] = 'Morarach_E15.5'

In [7]:
morarach_e15_ad.obs['sample'] = 'cell'

In [8]:
morarach_e15_ad.obs = morarach_e15_ad.obs[['barcode', 'age', 'dataset', 'sample']]

In [9]:
morarach_e15_ad.obs.head()

                               barcode    age         dataset sample
AAACCTGAGACCTTTG-1  AAACCTGAGACCTTTG-1  E15.5  Morarach_E15.5   cell
AAACCTGGTAAGTGGC-1  AAACCTGGTAAGTGGC-1  E15.5  Morarach_E15.5   cell
AAACCTGGTTACGCGC-1  AAACCTGGTTACGCGC-1  E15.5  Morarach_E15.5   cell
AAACGGGAGATGCCAG-1  AAACGGGAGATGCCAG-1  E15.5  Morarach_E15.5   cell
AAACGGGAGCTAAGAT-1  AAACGGGAGCTAAGAT-1  E15.5  Morarach_E15.5   cell

In [10]:
morarach_e15_ad.var['gene_name'] = morarach_e15_ad.var_names

In [11]:
morarach_e15_ad.var = morarach_e15_ad.var[['gene_name']]

In [12]:
morarach_e15_ad.var.head()

        gene_name
Xkr4         Xkr4
Gm1992     Gm1992
Gm37381   Gm37381
Rp1           Rp1
Rp1-1       Rp1-1

In [15]:
for key in list(morarach_e15_ad.layers.keys()):
    if key not in ['raw_counts', 'norm_counts', 'log_counts']:
        del morarach_e15_ad.layers[key]

In [16]:
morarach_e15_ad = ad.AnnData(X = morarach_e15_ad.X,
                             obs = morarach_e15_ad.obs.copy(),
                             var = morarach_e15_ad.var.copy(),
                             layers = morarach_e15_ad.layers.copy()
                            )

In [17]:
morarach_e15_ad

AnnData object with n_obs × n_vars = 3230 × 27998
    obs: 'barcode', 'age', 'dataset', 'sample'
    var: 'gene_name'
    layers: 'log_counts', 'norm_counts', 'raw_counts'

## Morarach E18.5

In [18]:
morarach_e18_ad = sc.read_h5ad('preprocessed_datasets/morarach_E18.h5ad')

In [19]:
morarach_e18_ad.X = morarach_e18_ad.layers['raw_counts']

In [20]:
morarach_e18_ad.obs['barcode'] = morarach_e18_ad.obs_names

In [21]:
morarach_e18_ad.obs['age'] = 'E18.5'
morarach_e18_ad.obs['dataset'] = 'Morarach_E18.5'

In [22]:
morarach_e18_ad.obs['sample'] = 'cell'

In [23]:
morarach_e18_ad.obs = morarach_e18_ad.obs[['barcode', 'age', 'dataset', 'sample']]

In [24]:
morarach_e18_ad.obs.head()

                               barcode    age         dataset sample
AAACCTGAGATCCGAG-1  AAACCTGAGATCCGAG-1  E18.5  Morarach_E18.5   cell
AAACCTGAGTGGAGAA-1  AAACCTGAGTGGAGAA-1  E18.5  Morarach_E18.5   cell
AAACCTGAGTGTACCT-1  AAACCTGAGTGTACCT-1  E18.5  Morarach_E18.5   cell
AAACCTGCATAAAGGT-1  AAACCTGCATAAAGGT-1  E18.5  Morarach_E18.5   cell
AAACCTGGTAACGCGA-1  AAACCTGGTAACGCGA-1  E18.5  Morarach_E18.5   cell

In [25]:
morarach_e18_ad.var['gene_name'] = morarach_e18_ad.var_names

In [26]:
morarach_e18_ad.var = morarach_e18_ad.var[['gene_name']]

In [27]:
morarach_e18_ad.var.head()

        gene_name
Xkr4         Xkr4
Gm1992     Gm1992
Gm37381   Gm37381
Rp1           Rp1
Rp1-1       Rp1-1

In [28]:
for key in list(morarach_e18_ad.layers.keys()):
    if key not in ['raw_counts', 'norm_counts', 'log_counts']:
        del morarach_e18_ad.layers[key]

In [29]:
morarach_e18_ad

AnnData object with n_obs × n_vars = 2663 × 27998
    obs: 'barcode', 'age', 'dataset', 'sample'
    var: 'gene_name'
    uns: 'hvg', 'leiden', 'leiden_colors', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    layers: 'log_counts', 'norm_counts', 'raw_counts'
    obsp: 'connectivities', 'distances'

In [30]:
morarach_e18_ad = ad.AnnData(X = morarach_e18_ad.X,
                             obs = morarach_e18_ad.obs.copy(),
                             var = morarach_e18_ad.var.copy(),
                             layers = morarach_e18_ad.layers.copy()
                            )

In [31]:
morarach_e18_ad

AnnData object with n_obs × n_vars = 2663 × 27998
    obs: 'barcode', 'age', 'dataset', 'sample'
    var: 'gene_name'
    layers: 'log_counts', 'norm_counts', 'raw_counts'

## Wright E17.5

In [32]:
wright_ad = sc.read_h5ad('preprocessed_datasets/wright_E17.h5ad')

In [33]:
wright_ad.X = wright_ad.layers['raw_counts']

In [34]:
wright_ad.obs['barcode'] = wright_ad.obs_names

In [35]:
wright_ad.obs['age'] = 'E17.5'
wright_ad.obs['dataset'] = 'Wright_E17.5'

In [36]:
wright_ad.obs['sample'] = 'nucleus'

In [37]:
wright_ad.obs = wright_ad.obs[['barcode', 'age', 'dataset', 'sample']]

In [38]:
wright_ad.obs.head()

                               barcode    age       dataset   sample
AAACGGGTCAGGTTCA-1  AAACGGGTCAGGTTCA-1  E17.5  Wright_E17.5  nucleus
AAAGATGCAAACCTAC-1  AAAGATGCAAACCTAC-1  E17.5  Wright_E17.5  nucleus
AAAGATGCATTGGCGC-1  AAAGATGCATTGGCGC-1  E17.5  Wright_E17.5  nucleus
AAAGATGGTACGAAAT-1  AAAGATGGTACGAAAT-1  E17.5  Wright_E17.5  nucleus
AAAGATGTCTACCAGA-1  AAAGATGTCTACCAGA-1  E17.5  Wright_E17.5  nucleus

In [39]:
wright_ad.var['gene_name'] = wright_ad.var_names

In [40]:
wright_ad.var = wright_ad.var[['gene_name']]

In [41]:
wright_ad.var.head()

        gene_name
Xkr4         Xkr4
Gm1992     Gm1992
Gm37381   Gm37381
Rp1           Rp1
Rp1-1       Rp1-1

In [42]:
for key in list(wright_ad.layers.keys()):
    if key not in ['raw_counts', 'norm_counts', 'log_counts']:
        del wright_ad.layers[key]

In [43]:
wright_ad = ad.AnnData(X = wright_ad.X,
                       obs = wright_ad.obs.copy(),
                       var = wright_ad.var.copy(),
                       layers = wright_ad.layers.copy()
                      )

In [44]:
wright_ad

AnnData object with n_obs × n_vars = 667 × 27990
    obs: 'barcode', 'age', 'dataset', 'sample'
    var: 'gene_name'
    layers: 'log_counts', 'norm_counts', 'raw_counts'

## Fine E14.5

In [45]:
fine_ad = sc.read_h5ad('preprocessed_datasets/fine_E14.h5ad')

In [46]:
fine_ad.X = fine_ad.layers['raw_counts']

In [47]:
fine_ad.obs['barcode'] = fine_ad.obs_names

In [48]:
fine_ad.obs['age'] = 'E14.5'
fine_ad.obs['dataset'] = 'Fine_E14.5'

In [49]:
fine_ad.obs['sample'] = 'cell'

In [50]:
fine_ad.obs = fine_ad.obs[['barcode', 'age', 'dataset', 'sample']]

In [51]:
fine_ad.obs.head()

,barcode,age,dataset,sample
E14.5_1_AAACCCATCGAGCTGC-1,E14.5_1_AAACCCATCGAGCTGC-1,E14.5,Fine_E14.5,cell
E14.5_1_AAACGAAGTCCTGAAT-1,E14.5_1_AAACGAAGTCCTGAAT-1,E14.5,Fine_E14.5,cell
E14.5_1_AAAGGATGTCTCGCGA-1,E14.5_1_AAAGGATGTCTCGCGA-1,E14.5,Fine_E14.5,cell
E14.5_1_AAAGGGCAGGGCTAAC-1,E14.5_1_AAAGGGCAGGGCTAAC-1,E14.5,Fine_E14.5,cell
E14.5_1_AAAGGGCAGTAATCCC-1,E14.5_1_AAAGGGCAGTAATCCC-1,E14.5,Fine_E14.5,cell

In [52]:
fine_ad.var['gene_name'] = fine_ad.var_names

In [53]:
fine_ad.var = fine_ad.var[['gene_name']]

In [54]:
fine_ad.var.head()

        gene_name
Xkr4         Xkr4
Gm1992     Gm1992
Gm19938   Gm19938
Rp1           Rp1
Sox17       Sox17

In [55]:
for key in list(fine_ad.layers.keys()):
    if key not in ['raw_counts', 'norm_counts', 'log_counts']:
        del fine_ad.layers[key]

In [56]:
fine_ad = ad.AnnData(X = fine_ad.X,
                       obs = fine_ad.obs.copy(),
                       var = fine_ad.var.copy(),
                       layers = fine_ad.layers.copy()
                      )

In [57]:
fine_ad

AnnData object with n_obs × n_vars = 1384 × 24900
    obs: 'barcode', 'age', 'dataset', 'sample'
    var: 'gene_name'
    layers: 'log_counts', 'norm_counts', 'raw_counts'

# Concatenation

In [58]:
combined_ad = morarach_e15_ad.concatenate(morarach_e18_ad, wright_ad, fine_ad, batch_key='batch', join='outer')

/loc/scratch/59801963/ipykernel_26649/2764292148.py:1: FutureWarning: Use anndata.concat instead of AnnData.concatenate, AnnData.concatenate is deprecated and will be removed in the future. See the tutorial for concat at: https://anndata.readthedocs.io/en/latest/concatenation.html
  combined_ad = morarach_e15_ad.concatenate(morarach_e18_ad, wright_ad, fine_ad, batch_key='batch', join='outer')

In [59]:
combined_ad.shape

(7944, 32101)

In [60]:
combined_ad.obs = combined_ad.obs.drop(columns={'barcode'})

In [61]:
combined_ad.obs.index.name = 'barcode'

In [62]:
combined_ad.obs

                                age         dataset sample batch
barcode
AAACCTGAGACCTTTG-1-0          E15.5  Morarach_E15.5   cell     0
AAACCTGGTAAGTGGC-1-0          E15.5  Morarach_E15.5   cell     0
AAACCTGGTTACGCGC-1-0          E15.5  Morarach_E15.5   cell     0
AAACGGGAGATGCCAG-1-0          E15.5  Morarach_E15.5   cell     0
AAACGGGAGCTAAGAT-1-0          E15.5  Morarach_E15.5   cell     0
...                             ...             ...    ...   ...
E14.5_2_TTTCCTCGTGAGTGAC-1-3  E14.5      Fine_E14.5   cell     3
E14.5_2_TTTCCTCTCAGACCTA-1-3  E14.5      Fine_E14.5   cell     3
E14.5_2_TTTCGATGTACACGCC-1-3  E14.5      Fine_E14.5   cell     3
E14.5_2_TTTGATCCAATAACGA-1-3  E14.5      Fine_E14.5   cell     3
E14.5_2_TTTGGAGCACGAAAGC-1-3  E14.5      Fine_E14.5   cell     3

[7944 rows x 4 columns]

In [63]:
combined_ad.var.head(10)

                 gene_name-0    gene_name-1    gene_name-2    gene_name-3
0610005C13Rik            NaN            NaN            NaN  0610005C13Rik
0610006L08Rik            NaN            NaN            NaN  0610006L08Rik
0610007P14Rik  0610007P14Rik  0610007P14Rik  0610007P14Rik            NaN
0610009B22Rik  0610009B22Rik  0610009B22Rik  0610009B22Rik  0610009B22Rik
0610009E02Rik            NaN            NaN            NaN  0610009E02Rik
0610009L18Rik  0610009L18Rik  0610009L18Rik  0610009L18Rik  0610009L18Rik
0610009O20Rik  0610009O20Rik  0610009O20Rik  0610009O20Rik            NaN
0610010F05Rik  0610010F05Rik  0610010F05Rik  0610010F05Rik  0610010F05Rik
0610010K14Rik  0610010K14Rik  0610010K14Rik  0610010K14Rik  0610010K14Rik
0610011F06Rik  0610011F06Rik  0610011F06Rik  0610011F06Rik            NaN

In [64]:
combined_ad.write_h5ad('concatenated_data.h5ad')